### ISSUE TITLE
Client unable to establish connection

### ISSUE THREAD

**Issue by iamroi** [snowflakedb/pdo_snowflake#185] opened 2019-04-06 22:15 UTC
The extension is working great but I'm getting the below error at random times on EC2 Ubuntu, Laravel. I'm using Laravel queue cron to run the script and it fails at PDOStatement->execute() randomly.

`PDOException: SQLSTATE[08001]: Client unable to establish connection: 240009 Request returned as being unsuccessful`

Any idea where this is going wrong?

**Comment by mrajabtech** [comment] 2019-04-08 23:01
Is there any update on this, please?

**Comment by notkriswagner** [comment] 2019-04-09 21:36
I **think** what is going on is that you're running a query with a connection that is expired and can't be renewed. The error that you got back is pretty generic so to be sure about my hunch, can you collect and post the following information:

1 ) System OS and version
2) PHP Version (including if it is a NTS build)
3) A code snippet of what you are running (as much as you feel comfortable exposing to us)
4) Log files from when the error occurred.

**Comment by sfc-gh-dszmolka** [comment] 2024-02-23 12:11
hi - there's been a couple releases since this issue was created (and unfortunately left largely unattended )
closing this issue for now but if it's still a problem, do comment please and I'll reopen. If you have a reproduction code snippet which can generally lead to the issue, that would be very helpful too.

**Closed by sfc-gh-dszmolka** 2024-02-23 12:11 UTC
Labels: bug
