### ISSUE TITLE
SNOW-1229299 Honor PDO Timeout Setting on Connections

### ISSUE THREAD

**Issue by sfc-gh-kwagner** [snowflakedb/pdo_snowflake#170] opened 2019-01-22 05:47 UTC
When a new connection is established, we should honor the connection timeout value specified by the PDO driver

**Comment by MerwaneHAMADI** [comment] 2023-02-13 15:30
Any update on this ?

**Comment by sfc-gh-dszmolka** [comment] 2024-02-23 12:13
hi - there's been a couple releases since this issue was raised, so closing this issue for now. If it's still a problem, do comment please and I'll reopen and we can look.

**Comment by aarefjev** [comment] 2024-03-08 15:28
> hi - there's been a couple releases since this issue was raised, so closing this issue for now. If it's still a problem, do comment please and I'll reopen and we can look.

Tested just now and issue still present :(
Very annoying as I cannot use PDO to export large chunks of data without some code workarounds.

**Comment by sfc-gh-dszmolka** [comment] 2024-03-11 14:21
did some tests and it appears that this is not so well documented 😓 but apparently we can rely on various [timeout settings](https://github.com/snowflakedb/pdo_snowflake/blob/v2.0.1/snowflake_driver.c#L586-L588) :
```cpp
        {"logintimeout",        "300",        0},
        {"maxhttpretries",      "7",          0},
        {"retrytimeout",        "300",        0}
```
starting from v2.0.1 and onwards, problem is that they stil don't seem to be taking effect although the driver correctly logs their altered value when using like
```php
$dbh = new PDO("snowflake:account=$account;logintimeout=3;retrytimeout=4;maxhttpretries=5", $user, $password);
```

we're taking a look further.

**Comment by sfc-gh-dszmolka** [comment] 2024-03-13 14:50
At this moment I can share the following updates from the dev team, hopefully clarifies some bits:

* `retrytimeout` can't be set to lower than 300 so in the test case it was set to 4 but actually 300 is used.
* `maxhttpretries` can't be set to lower than 7 so set it to 5 in the test, and actually 7 being used, it is expected
* `network_timeout` currently there is no way to set `network_timeout` in PHP driver, while the actual timeout being used is the lower one of `network_timeout` and `retrytimeout` and the default value for `network_timeout` of 0 is [considered unlimited](https://github.com/snowflakedb/libsnowflakeclient/blob/master/lib/connection.c#L1307) . so if `network_timeout`=0 and `retrytimeout`=300, the actual timeout would be 300
* `login timeout`: it can be set to 3 and expected to work, we're still investigating why it did not.
* unfortunately for now `retrytimeout` only works for login/query requests, chunk downloading is using hardcoded timeout of 60 seconds.

so hard to estimate the fix, because partly it works as expected (just I used unexpected values for my test), partly it really seems to be bug-ish, partly is an enhancement for e.g. chunk downloading which does not have a controllable timeout today

i'll post any new information in the same thread and thank you for bearing with us !

**Comment by sfc-gh-dszmolka** [comment] 2024-03-18 07:35
This is confirmed to be a bug in the underlying libsnowflakeclient.

Currently the retry timeout (or network timeout) would only work as expected when it's longer than the default timeout (`CURLOPT_CONNECTTIMEOUT`, `CURLOPT_TIMEOUT`) or there is no network issue and the server send back a retry-able http error.

Driver team will make fix on the libsnowflakeclient side, both the timeout issue and the retry behavior for chunk downloading.

**Comment by sfc-gh-dszmolka** [comment] 2024-03-20 07:32
PR (in the underlying libsnowflakeclient) https://github.com/snowflakedb/libsnowflakeclient/pull/683

**Comment by sfc-gh-dszmolka** [comment] 2024-03-21 08:14
PR merged and will be released with the next version of the PHP driver, which first needs to be rebased on the new release from libsnowflakeclient which actually contains the fix. Have no timeline on this at this moment but will update this thread.

**Comment by sfc-gh-dszmolka** [comment] 2024-03-28 16:00
quick update: [fixed libsnowflakeclient](https://github.com/snowflakedb/libsnowflakeclient/releases/tag/v1.0.8) now released and we're targeting 2024 April (~end of month) to release the new PHP driver based on that.

**Comment by sfc-gh-dszmolka** [comment] 2024-04-29 11:03
fix is available with the fresh release of Snowflake PHP driver v2.0.3

**Closed by sfc-gh-dszmolka** 2024-04-29 11:03 UTC
Labels: bug, status-triage_done, status-fixed_awaiting_release
